{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.projectId }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.serviceAccountRef }}
{{- end }}
