{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.projectId }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.serviceAccountRef }}
          clusterName: {{ .Values.externalSecrets.secretStore.clusterName | quote }}
          clusterLocation: {{ .Values.externalSecrets.secretStore.clusterLocation | quote }}

{{- end }}
